import {readFile} from 'node:fs/promises';
const root=new URL('./',import.meta.url);
const seed=await readFile(new URL('presentations/compania-avvero.html',root),'utf8');
const page=await readFile(new URL('public/index.html',root),'utf8');
const logo='data:image/png;base64,'+(await readFile(new URL('public/logo.png',root))).toString('base64');
const base={id:'compania-avvero',title:'Prezentarea companiei Avvero',createdAt:'2026-10-05T00:00:00.000Z'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const htmlHeaders={'content-type':'text/html; charset=utf-8','x-content-type-options':'nosniff','cache-control':'no-store','content-security-policy':"sandbox allow-scripts allow-popups allow-downloads; frame-ancestors 'self'"};
export default {async fetch(request,env){try{const url=new URL(request.url);const path=url.pathname;
if(path==='/logo.png'&&request.method==='GET'){const b64=logo.split(',')[1];return new Response(Uint8Array.from(atob(b64),c=>c.charCodeAt(0)),{headers:{'content-type':'image/png','cache-control':'public,max-age=86400'}})}
if(path==='/'&&request.method==='GET')return new Response(page,{headers:{'content-type':'text/html; charset=utf-8','x-content-type-options':'nosniff','content-security-policy':"frame-ancestors 'self'"}});
if(path==='/api/presentations'&&request.method==='GET'){if(!env.FILES)return json({error:'Spațiul pentru prezentări nu este disponibil.'},503);let objects=[],cursor;do{const batch=await env.FILES.list({prefix:'presentations/',cursor,include:['customMetadata']});objects.push(...batch.objects);cursor=batch.truncated?batch.cursor:undefined}while(cursor);return json([base,...objects.map(x=>({id:x.key.slice(14),title:x.customMetadata?.title||'Prezentare',createdAt:x.customMetadata?.createdAt||x.uploaded.toISOString()})).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))])}
if(path==='/api/presentations'&&request.method==='POST'){if(request.headers.get('origin')!==url.origin)return json({error:'Cerere nepermisă.'},403);if(!env.FILES)return json({error:'Spațiul pentru prezentări nu este disponibil.'},503);const length=Number(request.headers.get('content-length'));if(length>21*1024*1024)return json({error:'Fișierul depășește 20 MB.'},413);const form=await request.formData();const file=form.get('file');const title=String(form.get('title')||'').trim();if(!file||typeof file.text!=='function'||!title||title.length>120||!/^.*\.html?$/i.test(file.name))return json({error:'Adaugă un fișier HTML și un titlu de maximum 120 de caractere.'},400);if(file.size>20*1024*1024)return json({error:'Fișierul depășește 20 MB.'},413);const html=await file.text();if(!/<(?:!doctype\s+html|html|head|body)[\s>]/i.test(html))return json({error:'Fișierul nu conține o pagină HTML.'},400);const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(html));const id=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');const existing=await env.FILES.head('presentations/'+id);if(existing)return json({id,title:existing.customMetadata.title,createdAt:existing.customMetadata.createdAt,existing:true});const createdAt=new Date().toISOString();await env.FILES.put('presentations/'+id,html,{httpMetadata:{contentType:'text/html; charset=utf-8'},customMetadata:{title,createdAt}});return json({id,title,createdAt},201)}
if(path.startsWith('/presentations/')&&request.method==='GET'){const id=path.slice(15);if(id===base.id)return new Response(seed,{headers:htmlHeaders});if(!/^[a-f0-9]{64}$/.test(id))return new Response('Prezentarea nu există.',{status:404});if(!env.FILES)return new Response('Prezentările nu sunt disponibile.',{status:503});const object=await env.FILES.get('presentations/'+id);return object?new Response(object.body,{headers:htmlHeaders}):new Response('Prezentarea nu există.',{status:404})}
return new Response('Pagina nu există.',{status:404})}catch(error){console.error('Presentation request failed',error.message);return json({error:'Nu am putut finaliza operațiunea. Încearcă din nou.'},500)}}};
