import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHandler,prefix} from '../lib/handler.js';
const hash='a'.repeat(64);const title='Prezentare cu diacritice: Învățare';const pathname=prefix+hash+'/'+Buffer.from(title).toString('base64url')+'.html';
function setup(env={BLOB_READ_WRITE_TOKEN:'mock-token',UPLOAD_PASSWORD:'secret'}){const blobs=[];let tokenOptions;const handler=createHandler({env,list:async({prefix:searchPrefix})=>({blobs:blobs.filter(b=>b.pathname.startsWith(searchPrefix)),hasMore:false}),get:async p=>blobs.some(b=>b.pathname===p)?{statusCode:200,stream:new Blob(['<!doctype html><html><body>Test</body></html>']).stream()}:null,handleUpload:async opts=>{if(opts.body.type==='blob.generate-client-token'){tokenOptions=await opts.onBeforeGenerateToken(opts.body.payload.pathname,opts.body.payload.clientPayload);return{clientToken:'fake-client-token'}}await opts.onUploadCompleted({blob:{},tokenPayload:null});return{response:'ok'}}});return{handler,blobs,get tokenOptions(){return tokenOptions}}}
const request=(route,body,origin='https://app.test')=>new Request('https://app.test/api/index?route='+route,{method:body?'POST':'GET',headers:{origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
test('First presentation loads without Blob or a writable disk',async()=>{const {handler}=setup({});const r=await handler(request('presentations'));assert.equal(r.status,200);assert.equal((await r.json())[0].id,'compania-avvero');const config=await(await handler(request('config'))).json();assert.equal(config.uploadReady,false);assert.equal((await handler(request('prepare',{hash,title,password:'secret'}))).status,503)});
test('Prepare validates password, origin and title before upload',async()=>{const {handler}=setup();assert.equal((await handler(request('prepare',{hash,title,password:'wrong'}))).status,401);assert.equal((await handler(request('prepare',{hash,title,password:'secret'},'https://other.test'))).status,403);assert.equal((await handler(request('prepare',{hash:'bad',title,password:'secret'}))).status,400);const r=await handler(request('prepare',{hash,title,password:'secret'}));assert.equal(r.status,200);assert.equal((await r.json()).pathname,pathname)});
test('Direct upload issues a limited token only after authorization',async()=>{const s=setup();const body={type:'blob.generate-client-token',payload:{pathname,clientPayload:JSON.stringify({password:'secret'})}};assert.equal((await s.handler(request('upload',body))).status,200);assert.equal(s.tokenOptions.maximumSizeInBytes,20*1024*1024);assert.equal(s.tokenOptions.allowOverwrite,false);assert.deepEqual(s.tokenOptions.allowedContentTypes,['text/html']);body.payload.clientPayload=JSON.stringify({password:'wrong'});assert.equal((await s.handler(request('upload',body))).status,401);body.payload.pathname='../bad.html';body.payload.clientPayload=JSON.stringify({password:'secret'});assert.equal((await s.handler(request('upload',body))).status,400)});
test('Stored presentation is listed, streamed and recognized as duplicate',async()=>{const s=setup();s.blobs.push({pathname,uploadedAt:new Date()});const list=await(await s.handler(request('presentations'))).json();assert.equal(list.length,2);assert.equal(list[1].title,title);const result=await(await s.handler(request('prepare',{hash,title,password:'secret'}))).json();assert.equal(result.existing,true);const r=await s.handler(new Request('https://app.test/api/index?route=content&id='+hash));assert.equal(r.status,200);assert.equal(r.headers.get('Content-Type'),'text/plain; charset=utf-8');assert.match(await r.text(),/<body>Test/);assert.equal((await s.handler(new Request('https://app.test/api/index?route=content&id=bad'))).status,404)});
test('Signed callback does not require a browser origin',async()=>{const {handler}=setup();const r=await handler(new Request('https://app.test/api/index?route=upload',{method:'POST',body:JSON.stringify({type:'blob.upload-completed',payload:{}})}));assert.equal(r.status,200)});
test('UI and package preserve header upload and avoid local disk storage',async()=>{const page=await readFile('public/index.html','utf8');assert.equal((page.match(/id="choose"/g)||[]).length,1);assert.match(page,/<header>[\s\S]*upload-button/);assert.doesNotMatch(page,/<aside/);const cfg=JSON.parse(await readFile('vercel.json','utf8'));assert.equal(cfg.outputDirectory,'public');assert.equal(cfg.framework,null);assert.match(await readFile('public/presentations/compania-avvero.html','utf8'),/Prezentarea companiei/);const source=await readFile('lib/handler.js','utf8');assert.doesNotMatch(source,/mkdir|writeFile|localStorage/)});
