import {createHmac,randomUUID,timingSafeEqual} from 'node:crypto';
export const accessConfigured=env=>/^\d{4}$/.test(env.ACCESS_PIN||'')&&typeof env.ACCESS_SECRET==='string'&&env.ACCESS_SECRET.length>=32;
const fail=(error,status,code)=>Object.assign(new Error(error),{status,code});
const signature=(payload,secret)=>createHmac('sha256',secret).update(payload).digest('base64url');
export function createAccess(env){const attempts=new Map();
function requireConfiguration(){if(!accessConfigured(env))throw fail('Configurează ACCESS_PIN (4 cifre) și ACCESS_SECRET (minimum 32 de caractere) în Vercel, apoi fă Redeploy.',503,'ACCESS_SETUP');}
function issue(pin,request){requireConfiguration();const origin=request.headers.get('origin');if(!origin||new URL(origin).origin!==new URL(request.url).origin)throw fail('Cerere nepermisă.',403);const now=Date.now();const key=request.headers.get('x-vercel-forwarded-for')||request.headers.get('x-forwarded-for')||'unknown';if(attempts.size>10000)for(const [k,v] of attempts)if(v.until<now)attempts.delete(k);const previous=attempts.get(key);if(previous?.until>now&&previous.count>=5)throw fail('Prea multe încercări. Reîncearcă peste 15 minute.',429);const expected=Buffer.from(env.ACCESS_PIN);const supplied=Buffer.from(typeof pin==='string'?pin:'');if(supplied.length!==4||!/^\d{4}$/.test(pin)||!timingSafeEqual(supplied,expected)){const entry=previous?.until>now?previous:{count:0,until:now+15*60*1000};entry.count++;attempts.set(key,entry);throw fail('PIN incorect. Încearcă din nou.',401,'INVALID_PIN');}attempts.delete(key);const expiresAt=now+30*60*1000;const payload=Buffer.from(JSON.stringify({expiresAt,nonce:randomUUID(),version:signature(env.ACCESS_PIN,env.ACCESS_SECRET)})).toString('base64url');return{token:payload+'.'+signature(payload,env.ACCESS_SECRET),expiresAt};}
function requireAccess(request){requireConfiguration();const value=request.headers.get('authorization')||'';if(value.length>2048||!value.startsWith('Bearer '))throw fail('Introdu PIN-ul pentru acces.',401,'ACCESS_REQUIRED');const parts=value.slice(7).split('.');if(parts.length!==2)throw fail('Introdu PIN-ul pentru acces.',401,'ACCESS_REQUIRED');const expected=Buffer.from(signature(parts[0],env.ACCESS_SECRET));const supplied=Buffer.from(parts[1]);if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected))throw fail('Introdu PIN-ul pentru acces.',401,'ACCESS_REQUIRED');let data;try{data=JSON.parse(Buffer.from(parts[0],'base64url').toString());}catch{throw fail('Introdu PIN-ul pentru acces.',401,'ACCESS_REQUIRED');}if(!Number.isFinite(data.expiresAt)||data.expiresAt<=Date.now()||data.expiresAt>Date.now()+30*60*1000||data.version!==signature(env.ACCESS_PIN,env.ACCESS_SECRET))throw fail('Introdu PIN-ul pentru acces.',401,'ACCESS_REQUIRED');}
return{issue,requireAccess};}
