import {createHash,timingSafeEqual} from 'node:crypto';
export const prefix='avvero-grow-up/presentations/';
export const seed={id:'compania-avvero',title:'Prezentarea companiei Avvero',createdAt:'2026-10-05T00:00:00.000Z'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(message,status)=>Object.assign(new Error(message),{status});
const digest=value=>createHash('sha256').update(value).digest();
function titleFromPath(pathname){const match=pathname.match(/^avvero-grow-up\/presentations\/([a-f0-9]{64})\/([A-Za-z0-9_-]{1,640})\.html$/);if(!match)return null;const title=Buffer.from(match[2],'base64url').toString('utf8');if(!title.trim()||title.length>120)return null;return{id:match[1],title};}
export function createHandler({list,get,handleUpload,env=process.env}){
async function allBlobs(searchPrefix=prefix){let blobs=[],cursor;do{const batch=await list({prefix:searchPrefix,cursor,limit:1000,token:env.BLOB_READ_WRITE_TOKEN});blobs.push(...batch.blobs);cursor=batch.hasMore?batch.cursor:undefined;}while(cursor);return blobs;}
function configured(){if(!env.BLOB_READ_WRITE_TOKEN)throw fail('Conectează un store Vercel Blob privat la proiect, apoi fă Redeploy.',503);}
function authorize(request,supplied){if(!env.UPLOAD_PASSWORD)throw fail('Configurează UPLOAD_PASSWORD în Vercel, apoi fă Redeploy.',503);if(typeof supplied!=='string'||supplied.length>1024||!timingSafeEqual(digest(supplied),digest(env.UPLOAD_PASSWORD)))throw fail('Parola pentru încărcare este incorectă.',401);const origin=request.headers.get('origin');if(!origin||new URL(origin).host!==new URL(request.url).host)throw fail('Cerere nepermisă.',403);}
async function readJSON(request){const text=await request.text();if(Buffer.byteLength(text)>16384)throw fail('Cerere prea mare.',413);try{return JSON.parse(text)}catch{throw fail('Date invalide.',400)}}
return async function handler(request){try{const url=new URL(request.url);const route=url.searchParams.get('route')||url.pathname.split('/').pop();
if(route==='config'&&request.method==='GET')return json({requiresPassword:true,storageReady:!!env.BLOB_READ_WRITE_TOKEN,uploadReady:!!env.BLOB_READ_WRITE_TOKEN&&!!env.UPLOAD_PASSWORD});
if(route==='presentations'&&request.method==='GET'){if(!env.BLOB_READ_WRITE_TOKEN)return json([seed]);const blobs=await allBlobs();const seen=new Set();const records=blobs.map(b=>{const parsed=titleFromPath(b.pathname);return parsed?{...parsed,createdAt:new Date(b.uploadedAt).toISOString()}:null}).filter(Boolean).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).filter(r=>{if(seen.has(r.id))return false;seen.add(r.id);return true});return json([seed,...records]);}
if(route==='prepare'&&request.method==='POST'){configured();const data=await readJSON(request);authorize(request,data.password);if(typeof data.hash!=='string'||!/^[a-f0-9]{64}$/.test(data.hash)||typeof data.title!=='string'||!data.title.trim()||data.title.trim().length>120)throw fail('Titlu sau fișier invalid.',400);const existing=(await allBlobs(prefix+data.hash+'/')).find(b=>titleFromPath(b.pathname));if(existing){const parsed=titleFromPath(existing.pathname);return json({...parsed,createdAt:new Date(existing.uploadedAt).toISOString(),existing:true})}const title=data.title.trim();return json({id:data.hash,title,pathname:prefix+data.hash+'/'+Buffer.from(title).toString('base64url')+'.html'});}
if(route==='upload'&&request.method==='POST'){configured();const body=await readJSON(request);const response=await handleUpload({request,body,token:env.BLOB_READ_WRITE_TOKEN,onBeforeGenerateToken:async(pathname,clientPayload)=>{let data;try{data=JSON.parse(clientPayload||'{}')}catch{throw fail('Date invalide.',400)}authorize(request,data.password);const parsed=titleFromPath(pathname);if(!parsed)throw fail('Cale de încărcare invalidă.',400);if((await allBlobs(prefix+parsed.id+'/')).some(b=>titleFromPath(b.pathname)))throw fail('Prezentarea există deja. Reîncarcă lista.',409);return{allowedContentTypes:['text/html'],maximumSizeInBytes:20*1024*1024,addRandomSuffix:false,allowOverwrite:false,validUntil:Date.now()+15*60*1000};},onUploadCompleted:async()=>{}});return json(response);}
if(route==='content'&&request.method==='GET'){configured();const id=url.searchParams.get('id');if(!id||!/^[a-f0-9]{64}$/.test(id))throw fail('Prezentarea nu există.',404);const blob=(await allBlobs(prefix+id+'/')).find(b=>titleFromPath(b.pathname));if(!blob)throw fail('Prezentarea nu există.',404);const item=await get(blob.pathname,{access:'private',token:env.BLOB_READ_WRITE_TOKEN});if(!item||item.statusCode!==200||!item.stream)throw fail('Prezentarea nu există.',404);return new Response(item.stream,{headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
return json({error:'Pagina nu există.'},404);
}catch(error){if(!error.status)console.error('Presentation request failed:',error.name);return json({error:error.status?error.message:'Nu am putut accesa prezentările. Verifică store-ul Blob conectat la proiect.'},error.status||503)}};}
