import {upload,uploadPresigned} from '@vercel/blob/client';

const $=id=>document.getElementById(id);let records=[],pending=null,busy=false,requiresPassword=true;fetch('/api/config').then(r=>r.json()).then(c=>requiresPassword=c.requiresPassword).catch(()=>{});
function message(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error)}
async function api(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok){const err=new Error(data.error||'Nu am putut salva. Încearcă din nou.');err.status=r.status;throw err;}return data}
function render(){const holder=$('cards');holder.replaceChildren();$('count').textContent=records.length===1?'1 prezentare':records.length+' prezentări';if(!records.length){const empty=document.createElement('div');empty.className='empty';empty.innerHTML='<span class="empty-mark">＋</span><h3>Un nou început</h3><p>Prima ta prezentare începe aici.</p>';holder.append(empty);}for(const [i,item] of records.entries()){const card=document.createElement('article');card.className='card';const a=document.createElement('a');a.className='presentation';a.href='/?presentation='+encodeURIComponent(item.id);a.onclick=e=>{e.preventDefault();history.pushState(null,'',a.href);openPresentation(item.id);};const num=document.createElement('span');num.className='number';num.textContent=String(i+1).padStart(2,'0');const info=document.createElement('span');info.className='details';const title=document.createElement('strong');title.textContent=item.title;const sub=document.createElement('small');sub.textContent='Prezentare interactivă';info.append(title,sub);const open=document.createElement('span');open.className='open';open.textContent='Deschide ↗';a.append(num,info,open);const remove=document.createElement('button');remove.className='delete-button';remove.textContent='Șterge';remove.setAttribute('aria-label','Șterge '+item.title);remove.onclick=()=>{deleting=item;$('delete-title').textContent=item.title;$('delete-error').textContent='';$('delete-password').value='';$('delete-dialog').showModal();$('delete-password').focus();};card.append(a,remove);holder.append(card)}}
let deleting=null,deleteBusy=false,viewerAbort=null,returnFocus=null;
async function openPresentation(id){viewerAbort?.abort();viewerAbort=new AbortController();const signal=viewerAbort.signal;returnFocus=document.activeElement;$('viewer').hidden=false;document.body.classList.add('viewing');$('frame').removeAttribute('srcdoc');$('frame').hidden=true;$('viewer-status').hidden=false;$('viewer-status').textContent='Se încarcă prezentarea...';$('viewer-title').textContent=records.find(r=>r.id===id)?.title||'Prezentare';$('back').focus();try{const r=await fetch('/api/content?id='+encodeURIComponent(id),{signal});if(!r.ok){const data=await r.json();throw new Error(data.error||'Prezentarea nu poate fi deschisă.');}const html=await r.text();if(signal.aborted)return;$('frame').srcdoc=html;$('frame').hidden=false;$('viewer-status').hidden=true;}catch(e){if(e.name!=='AbortError')$('viewer-status').textContent=e.message;}}
function closePresentation(){viewerAbort?.abort();$('viewer').hidden=true;$('frame').removeAttribute('srcdoc');document.body.classList.remove('viewing');returnFocus?.focus();}
$('back').onclick=()=>{history.replaceState(null,'','/');closePresentation();};window.addEventListener('popstate',()=>{const id=new URLSearchParams(location.search).get('presentation');id?openPresentation(id):closePresentation();});
$('delete-cancel').onclick=()=>{if(!deleteBusy)$('delete-dialog').close();};$('delete-dialog').addEventListener('cancel',e=>{if(deleteBusy)e.preventDefault();});
$('delete-form').onsubmit=async e=>{e.preventDefault();if(!deleting||deleteBusy)return;deleteBusy=true;$('delete-save').disabled=true;$('delete-cancel').disabled=true;$('delete-error').textContent='';try{await api('/api/presentations',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:deleting.id,password:$('delete-password').value})});records=records.filter(r=>r.id!==deleting.id);render();$('delete-dialog').close();message('Prezentarea a fost ștearsă.');deleting=null;}catch(e){$('delete-error').textContent=e.message;}finally{deleteBusy=false;$('delete-save').disabled=false;$('delete-cancel').disabled=false;}};
document.addEventListener('click',e=>{const target=e.target.closest('button,.presentation');if(!target)return;const rect=target.getBoundingClientRect();const shine=document.createElement('span');shine.className='click-shine';shine.style.left=(e.clientX?e.clientX-rect.left:rect.width/2)+'px';shine.style.top=(e.clientY?e.clientY-rect.top:rect.height/2)+'px';target.append(shine);setTimeout(()=>shine.remove(),700);});
async function load(){try{records=await api('/api/presentations');render()}catch(e){$('cards').replaceChildren();message('Nu am putut încărca prezentările. Reîncarcă pagina.',true)}}
async function stage(file){if(busy||deleteBusy||$('dialog').open||$('delete-dialog').open||!$('viewer').hidden)return;if(!file)return;if(!/\.html?$/i.test(file.name)){message('Alege un fișier HTML, de exemplu index.html.',true);return}if(file.size>20*1024*1024){message('Fișierul depășește 20 MB.',true);return}try{const html=await file.text();if(!/<(?:!doctype\s+html|html|head|body)[\s>]/i.test(html)){message('Fișierul nu conține o pagină HTML.',true);return}const doc=new DOMParser().parseFromString(html,'text/html');const title=doc.title.trim();pending={file,html};$('password-group').hidden=!requiresPassword;$('title').value=(title||file.name.replace(/\.html?$/i,'')).slice(0,120);$('filename').textContent=file.name+' • '+(file.size/1024/1024).toFixed(1)+' MB';$('dialog-error').textContent='';$('dialog').showModal();$('title').focus();$('title').select()}catch(e){message('Nu am putut citi fișierul. Alege-l din nou.',true)}}
$('choose').onclick=()=>$('file').click();$('file').onchange=()=>{stage($('file').files[0]);$('file').value=''};
let dragDepth=0;document.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files'))e.preventDefault()});document.addEventListener('drop',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();$('drop').classList.remove('over');dragDepth=0;if(e.dataTransfer.files.length!==1){message('Adaugă câte o prezentare.',true);return}stage(e.dataTransfer.files[0])}});$('drop').addEventListener('dragenter',e=>{if(![...e.dataTransfer.types].includes('Files'))return;e.preventDefault();dragDepth++;$('drop').classList.add('over')});$('drop').addEventListener('dragleave',()=>{if(--dragDepth<=0)$('drop').classList.remove('over')});
$('cancel').onclick=()=>{if(!busy){$('dialog').close();pending=null}};$('dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();else pending=null});
$('form').onsubmit=async e=>{e.preventDefault();if(!pending||busy)return;const title=$('title').value.trim();if(!title){$('dialog-error').textContent='Scrie un titlu.';return}busy=true;$('save').disabled=true;$('cancel').disabled=true;$('save').textContent='Se adaugă...';$('dialog-error').textContent='';try{const bytes=await pending.file.arrayBuffer();const hashBytes=await crypto.subtle.digest('SHA-256',bytes);const hash=Array.from(new Uint8Array(hashBytes),b=>b.toString(16).padStart(2,'0')).join('');const prepared=await api('/api/prepare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hash,title,password:$('password').value})});let result=prepared;if(!prepared.existing){await (prepared.uploadMode==='oidc'?uploadPresigned:upload)(prepared.pathname,new Blob([bytes],{type:'text/html'}),{access:'private',contentType:'text/html',handleUploadUrl:'/api/upload',clientPayload:JSON.stringify({password:$('password').value}),multipart:true,onUploadProgress:({percentage})=>{$('save').textContent='Se adaugă... '+Math.round(percentage)+'%'}});result={id:prepared.id,title:prepared.title,createdAt:new Date().toISOString()};}if(!records.some(x=>x.id===result.id))records.push(result);render();$('dialog').close();pending=null;message(result.existing?'Prezentarea există deja. O găsești în listă.':'Prezentarea a fost adăugată.')}catch(e){if(e.status===401){$('password-group').hidden=false;$('password').focus();}$('dialog-error').textContent=e.message}finally{busy=false;$('save').disabled=false;$('cancel').disabled=false;$('save').textContent='Adaugă prezentarea'}};
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'list_presentations',title:'Lista prezentărilor',description:'Returnează prezentările din pagina Avvero Grow-Up.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Nu sunt acceptați parametri.');records=await api('/api/presentations');render();return records.map(({id,title})=>({id,title,url:'/?presentation='+encodeURIComponent(id)}))}},{signal:lifecycle.signal})).catch(()=>{});}catch(e){}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}load().then(()=>{const id=new URLSearchParams(location.search).get('presentation');if(id)openPresentation(id);});
