import {upload,uploadPresigned} from '@vercel/blob/client';

let accessToken='',accessTimer=null,unlocking=false;
const $=id=>document.getElementById(id);let records=[],pending=null,busy=false,requiresPassword=true;fetch('/api/config').then(r=>r.json()).then(c=>requiresPassword=c.requiresPassword).catch(()=>{});
function message(text,error=false){$('status').textContent=text;$('status').hidden=!text;$('status').classList.toggle('error',error)}
async function api(url,options){const headers=new Headers(options?.headers);if(accessToken)headers.set('Authorization','Bearer '+accessToken);let r;try{r=await fetch(url,{...options,headers})}catch{throw new Error('Conexiunea cu serverul a eșuat. Reîncarcă pagina și încearcă din nou.')}const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Serverul nu a răspuns corect. Reîncarcă pagina și încearcă din nou.')}if(!r.ok){if(data.code==='ACCESS_REQUIRED'){lock();}const err=new Error(data.error||'Nu am putut salva. Încearcă din nou.');err.status=r.status;throw err;}return data}
function render(){const holder=$('cards');holder.replaceChildren();$('count').textContent=records.length===1?'1 prezentare':records.length+' prezentări';for(const [i,item] of records.entries()){const card=document.createElement('article');card.className='card';const a=document.createElement('a');a.className='presentation';a.href='/'+encodeURIComponent(item.slug);a.onclick=e=>{e.preventDefault();history.pushState(null,'',a.href);openPresentation(item.id);};const num=document.createElement('span');num.className='number';num.textContent=String(i+1).padStart(2,'0');const info=document.createElement('span');info.className='details';const title=document.createElement('strong');title.textContent=item.title;const sub=document.createElement('small');sub.textContent='Prezentare interactivă';info.append(title,sub);const open=document.createElement('span');open.className='open';open.textContent='Deschide ↗';a.append(num,info,open);const remove=document.createElement('button');remove.className='delete-button';remove.innerHTML='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13M10 10v7m4-7v7" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';remove.title='Șterge prezentarea';remove.setAttribute('aria-label','Șterge '+item.title);remove.onclick=()=>{deleting=item;$('delete-title').textContent=item.title;$('delete-error').textContent='';$('delete-password').value='';$('delete-dialog').showModal();$('delete-password').focus();};card.append(a,remove);holder.append(card);card.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const rect=card.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height;card.style.setProperty('--gx',x*100+'%');card.style.setProperty('--gy',y*100+'%');card.style.setProperty('--rx',(0.5-y)*4+'deg');card.style.setProperty('--ry',(x-0.5)*4+'deg');});card.addEventListener('pointerleave',()=>{card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg');});}}
let deleting=null,deleteBusy=false,viewerAbort=null,returnFocus=null;
function makePresentationLogoStatic(html){const doc=new DOMParser().parseFromString(html,'text/html');for(const link of doc.querySelectorAll('header a.brand,a.brand[href]')){const replacement=doc.createElement('div');for(const attribute of link.attributes)if(attribute.name!=='href'&&attribute.name!=='target'&&attribute.name!=='rel')replacement.setAttribute(attribute.name,attribute.value);replacement.append(...link.childNodes);link.replaceWith(replacement)}let viewport=doc.querySelector('meta[name="viewport"]');if(!viewport){viewport=doc.createElement('meta');viewport.name='viewport';doc.head.prepend(viewport)}viewport.content='width=device-width,initial-scale=1,viewport-fit=cover';const safeArea=doc.createElement('style');safeArea.id='presentation-safe-area';safeArea.textContent='@media(max-width:700px){header{background:linear-gradient(180deg,rgba(5,31,38,.58) 0%,rgba(5,31,38,.44) calc(env(safe-area-inset-top) + 42px),rgba(5,31,38,.24) 78%,transparent 100%)!important}}';doc.head.append(safeArea);return '<!doctype html>\n'+doc.documentElement.outerHTML}
async function openPresentation(id){viewerAbort?.abort();viewerAbort=new AbortController();const signal=viewerAbort.signal;returnFocus=document.activeElement;$('viewer').hidden=false;document.body.classList.add('viewing');$('frame').removeAttribute('srcdoc');$('frame').hidden=true;$('viewer-status').hidden=false;$('viewer-status').textContent='Se încarcă prezentarea...';document.title=(records.find(r=>r.id===id)?.title||'Prezentare')+' | Avvero GROW-UP!';try{const r=await fetch('/api/content?id='+encodeURIComponent(id),{signal,headers:{Authorization:'Bearer '+accessToken}});if(!r.ok){const data=await r.json();if(data.code==='ACCESS_REQUIRED')lock();throw new Error(data.error||'Prezentarea nu poate fi deschisă.');}const html=await r.text();if(signal.aborted)return;$('frame').srcdoc=makePresentationLogoStatic(html);$('frame').hidden=false;$('viewer-status').hidden=true;}catch(e){if(e.name!=='AbortError')$('viewer-status').textContent=e.message;}}
function closePresentation(){viewerAbort?.abort();$('viewer').hidden=true;$('frame').removeAttribute('srcdoc');document.body.classList.remove('viewing');document.title='Avvero GROW-UP!';returnFocus?.focus();}
function route(){const legacy=new URLSearchParams(location.search).get('presentation');const slug=decodeURIComponent(location.pathname.replace(/^\/|\/$/g,''));const item=legacy?records.find(r=>r.id===legacy):records.find(r=>r.slug===slug);if(item){if(legacy)history.replaceState(null,'','/'+item.slug);openPresentation(item.id);}else if(slug||legacy){$('viewer').hidden=false;document.body.classList.add('viewing');$('frame').hidden=true;$('viewer-status').hidden=false;$('viewer-status').textContent='Prezentarea nu există.';}else closePresentation();}
window.addEventListener('popstate',route);
$('delete-cancel').onclick=()=>{if(!deleteBusy)$('delete-dialog').close();};$('delete-dialog').addEventListener('cancel',e=>{if(deleteBusy)e.preventDefault();});
$('delete-form').onsubmit=async e=>{e.preventDefault();if(!deleting||deleteBusy)return;deleteBusy=true;$('delete-save').disabled=true;$('delete-cancel').disabled=true;$('delete-error').textContent='';try{await api('/api/presentations',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:deleting.id,password:$('delete-password').value})});records=records.filter(r=>r.id!==deleting.id);render();$('delete-dialog').close();message('Prezentarea a fost ștearsă.');deleting=null;}catch(e){$('delete-error').textContent=e.message;}finally{deleteBusy=false;$('delete-save').disabled=false;$('delete-cancel').disabled=false;}};
document.addEventListener('click',e=>{const target=e.target.closest('button,.presentation');if(!target)return;const rect=target.getBoundingClientRect();const shine=document.createElement('span');shine.className='click-shine';shine.style.left=(e.clientX?e.clientX-rect.left:rect.width/2)+'px';shine.style.top=(e.clientY?e.clientY-rect.top:rect.height/2)+'px';target.append(shine);setTimeout(()=>shine.remove(),700);});
async function load(){try{records=await api('/api/presentations');render()}catch(e){$('cards').replaceChildren();message('Nu am putut încărca prezentările. Reîncarcă pagina.',true)}}
async function stage(file){if(busy||deleteBusy||$('dialog').open||$('delete-dialog').open||!$('viewer').hidden)return;if(!file)return;if(!/\.html?$/i.test(file.name)){message('Alege un fișier HTML, de exemplu index.html.',true);return}if(file.size>20*1024*1024){message('Fișierul depășește 20 MB.',true);return}try{const html=await file.text();if(!/<(?:!doctype\s+html|html|head|body)[\s>]/i.test(html)){message('Fișierul nu conține o pagină HTML.',true);return}const doc=new DOMParser().parseFromString(html,'text/html');const title=doc.title.trim();pending={file,html};$('password-group').hidden=!requiresPassword;$('title').value=(title||file.name.replace(/\.html?$/i,'')).slice(0,120);$('filename').textContent=file.name+' • '+(file.size/1024/1024).toFixed(1)+' MB';$('dialog-error').textContent='';$('dialog').showModal();$('title').focus();$('title').select()}catch(e){message('Nu am putut citi fișierul. Alege-l din nou.',true)}}
$('choose').onclick=()=>$('file').click();$('file').onchange=()=>{stage($('file').files[0]);$('file').value=''};
let dragDepth=0;document.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files'))e.preventDefault()});document.addEventListener('drop',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();$('drop').classList.remove('over');dragDepth=0;if(e.dataTransfer.files.length!==1){message('Adaugă câte o prezentare.',true);return}stage(e.dataTransfer.files[0])}});$('drop').addEventListener('dragenter',e=>{if(![...e.dataTransfer.types].includes('Files'))return;e.preventDefault();dragDepth++;$('drop').classList.add('over')});$('drop').addEventListener('dragleave',()=>{if(--dragDepth<=0)$('drop').classList.remove('over')});
$('cancel').onclick=()=>{if(!busy){$('dialog').close();pending=null}};$('dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();else pending=null});
$('form').onsubmit=async e=>{e.preventDefault();if(!pending||busy)return;const title=$('title').value.trim();if(!title){$('dialog-error').textContent='Scrie un titlu.';return}busy=true;$('save').disabled=true;$('cancel').disabled=true;$('save').textContent='Se adaugă...';$('dialog-error').textContent='';try{const bytes=await pending.file.arrayBuffer();const hashBytes=await crypto.subtle.digest('SHA-256',bytes);const hash=Array.from(new Uint8Array(hashBytes),b=>b.toString(16).padStart(2,'0')).join('');const prepared=await api('/api/prepare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hash,title,password:$('password').value})});let result=prepared;if(!prepared.existing){await (prepared.uploadMode==='oidc'?uploadPresigned:upload)(prepared.pathname,new Blob([bytes],{type:'text/html'}),{access:'private',contentType:'text/html',handleUploadUrl:'/api/upload',headers:{Authorization:'Bearer '+accessToken},clientPayload:JSON.stringify({password:$('password').value}),multipart:true,onUploadProgress:({percentage})=>{$('save').textContent='Se adaugă... '+Math.round(percentage)+'%'}});result={id:prepared.id,title:prepared.title,createdAt:new Date().toISOString()};}records=await api('/api/presentations');render();$('dialog').close();pending=null;message(result.existing?'Prezentarea există deja. O găsești în listă.':'Prezentarea a fost adăugată.')}catch(e){if(e.status===401){$('password-group').hidden=false;$('password').focus();}$('dialog-error').textContent=e.message}finally{busy=false;$('save').disabled=false;$('cancel').disabled=false;$('save').textContent='Adaugă prezentarea'}};
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'list_presentations',title:'Lista prezentărilor',description:'Returnează prezentările din pagina Avvero Grow-Up.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Nu sunt acceptați parametri.');records=await api('/api/presentations');render();return records.map(({id,title,slug})=>({id,title,url:'/'+slug}))}},{signal:lifecycle.signal})).catch(()=>{});}catch(e){}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}initializeAccess();

function lock(){for(const id of ['dialog','delete-dialog'])if($(id).open)$(id).close();pending=null;message('');accessToken='';clearTimeout(accessTimer);closePresentation();document.body.classList.add('locked');$('access-screen').hidden=false;$('cards').replaceChildren();records=[];$('count').textContent='0 prezentări';for(const input of document.querySelectorAll('.pin-digit'))input.value='';$('pin-0').focus();}
async function initializeAccess(){lock();try{const config=await api('/api/config');if(!config.accessConfigured)$('access-error').textContent='Configurează ACCESS_PIN și ACCESS_SECRET în Vercel, apoi fă Redeploy.';}catch(e){$('access-error').textContent='Nu am putut verifica accesul. Reîncarcă pagina.';}}
const digits=[...document.querySelectorAll('.pin-digit')];digits.forEach((input,index)=>{input.addEventListener('input',()=>{input.value=input.value.replace(/[^0-9]/g,'').slice(-1);$('access-error').textContent='';if(input.value&&index<3)digits[index+1].focus();if(digits.every(d=>d.value))$('access-form').requestSubmit();});input.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!input.value&&index>0){digits[index-1].value='';digits[index-1].focus();}if(e.key==='ArrowLeft'&&index>0)digits[index-1].focus();if(e.key==='ArrowRight'&&index<3)digits[index+1].focus();});input.addEventListener('paste',e=>{e.preventDefault();const value=e.clipboardData.getData('text').replace(/[^0-9]/g,'').slice(0,4);digits.forEach((d,i)=>d.value=value[i]||'');digits[Math.min(value.length,3)].focus();if(value.length===4)$('access-form').requestSubmit();});});
$('access-form').onsubmit=async e=>{e.preventDefault();if(unlocking)return;const pin=digits.map(d=>d.value).join('');if(!/^\d{4}$/.test(pin)){$('access-error').textContent='Introdu cele patru cifre.';return;}unlocking=true;digits.forEach(d=>d.disabled=true);$('access-form').setAttribute('aria-busy','true');$('access-error').textContent='';try{const result=await api('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});accessToken=result.token;accessTimer=setTimeout(lock,Math.max(0,result.expiresAt-Date.now()));$('access-screen').hidden=true;document.body.classList.remove('locked');digits.forEach(d=>d.value='');await load();route();}catch(e){$('access-error').textContent=e.message;digits.forEach(d=>d.value='');}finally{unlocking=false;digits.forEach(d=>d.disabled=false);$('access-form').removeAttribute('aria-busy');if(!accessToken)digits[0].focus();}};
window.addEventListener('pagehide',lock);window.addEventListener('pageshow',e=>{if(e.persisted)initializeAccess();});
